### ISSUE TITLE
island.cxx upper_bound not declared

### ISSUE THREAD

**Issue by a-elsaid** [travisdesell/exact#4]
/rnn/island.cxx:130:43: error: ‘upper_bound’ was not declared in this scope
     auto index_iterator = genomes.insert( upper_bound(genomes.begin(), genomes.end(), copy, sort_genomes_by_fitness()), copy);

**Comment by travisdesell** [comment]
Fixed this in the most recent commit. Added:
#include <algorithm>
using std::sort;
using std::upper_bound;

at the top of island.cxx
